version: '3.8'

services:
  backend-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    deploy:
      replicas: 1
    container_name: budgeto-backend
    restart: unless-stopped
    environment:
      - ConnectionStrings__BudgetoDb=${DB_CONNECTION_STRING}
      - Seed__AdminPassword=${SEED_ADMIN_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - db-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    container_name: budgeto-frontend
    restart: unless-stopped
    depends_on:
      - backend-api
    networks:
      - proxy-network
      - db-network
  

networks:
  db-network:
    external: true
    name: db-network
  proxy-network:
    external: true
    name: proxy-network