using Budgeto.Domain.Constants;
using Budgeto.Domain.Entities;
using Budgeto.Domain.Enums;
using Budgeto.Infrastructure.Identity;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Budgeto.Infrastructure.Data;

public static class InitialiserExtensions
{
    public static async Task InitialiseDatabaseAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();

        var initialiser =
            scope.ServiceProvider.GetRequiredService<ApplicationDbContextInitialiser>();

        await initialiser.InitialiseAsync();
        await initialiser.SeedAsync();
    }
}

public class ApplicationDbContextInitialiser
{
    private readonly ILogger<ApplicationDbContextInitialiser> _logger;
    private readonly ApplicationDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly IConfiguration _configuration;

    public ApplicationDbContextInitialiser(
        ILogger<ApplicationDbContextInitialiser> logger,
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
        IConfiguration configuration
    )
    {
        _logger = logger;
        _context = context;
        _userManager = userManager;
        _roleManager = roleManager;
        _configuration = configuration;
    }

    public async Task InitialiseAsync()
    {
        try
        {
            await _context.Database.EnsureCreatedAsync();
            await ApplySchemaUpdatesAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "An error occurred while initialising the database.");
            throw;
        }
    }

    private async Task ApplySchemaUpdatesAsync()
    {
        var conn = _context.Database.GetDbConnection();
        await conn.OpenAsync();

        using var cmd = conn.CreateCommand();

        // Add WeeklyLimit column to Budgets if missing
        cmd.CommandText = """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'Budgets' AND column_name = 'WeeklyLimit'
                ) THEN
                    ALTER TABLE "Budgets" ADD COLUMN "WeeklyLimit" numeric(18,2);
                END IF;
            END $$;
            """;
        await cmd.ExecuteNonQueryAsync();

        // Create SavingsGoals table if missing
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS "SavingsGoals" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(200) NOT NULL,
                "TargetAmount" numeric(18,2) NOT NULL,
                "CurrentAmount" numeric(18,2) NOT NULL DEFAULT 0,
                "Deadline" date,
                "Created" timestamp with time zone NOT NULL DEFAULT now(),
                "CreatedBy" text,
                "LastModified" timestamp with time zone NOT NULL DEFAULT now(),
                "LastModifiedBy" text
            );
            """;
        await cmd.ExecuteNonQueryAsync();

        // Create RecurringTransactions table if missing
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS "RecurringTransactions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(200) NOT NULL,
                "Amount" numeric(18,2) NOT NULL,
                "CategoryId" integer NOT NULL REFERENCES "Categories"("Id") ON DELETE CASCADE,
                "Frequency" integer NOT NULL DEFAULT 0,
                "NextDueDate" date NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT true,
                "Created" timestamp with time zone NOT NULL DEFAULT now(),
                "CreatedBy" text,
                "LastModified" timestamp with time zone NOT NULL DEFAULT now(),
                "LastModifiedBy" text
            );
            """;
        await cmd.ExecuteNonQueryAsync();

        // Create NetWorthAccounts table if missing
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS "NetWorthAccounts" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(200) NOT NULL,
                "Type" integer NOT NULL DEFAULT 0,
                "IsAsset" boolean NOT NULL DEFAULT true,
                "Balance" numeric(18,2) NOT NULL DEFAULT 0,
                "Created" timestamp with time zone NOT NULL DEFAULT now(),
                "CreatedBy" text,
                "LastModified" timestamp with time zone NOT NULL DEFAULT now(),
                "LastModifiedBy" text
            );
            """;
        await cmd.ExecuteNonQueryAsync();

        // Create NetWorthSnapshots table if missing
        cmd.CommandText = """
            CREATE TABLE IF NOT EXISTS "NetWorthSnapshots" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Month" integer NOT NULL,
                "Year" integer NOT NULL,
                "TotalAssets" numeric(18,2) NOT NULL DEFAULT 0,
                "TotalLiabilities" numeric(18,2) NOT NULL DEFAULT 0,
                "NetWorth" numeric(18,2) NOT NULL DEFAULT 0,
                "Created" timestamp with time zone NOT NULL DEFAULT now(),
                "CreatedBy" text,
                "LastModified" timestamp with time zone NOT NULL DEFAULT now(),
                "LastModifiedBy" text
            );
            """;
        await cmd.ExecuteNonQueryAsync();

        // Add unique index on (Month, Year) for snapshots
        cmd.CommandText = """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_NetWorthSnapshots_Month_Year"
            ON "NetWorthSnapshots" ("Month", "Year");
            """;
        await cmd.ExecuteNonQueryAsync();

        // Add RepaymentDate column to NetWorthAccounts if missing
        cmd.CommandText = """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'NetWorthAccounts' AND column_name = 'RepaymentDate'
                ) THEN
                    ALTER TABLE "NetWorthAccounts" ADD COLUMN "RepaymentDate" date;
                END IF;
            END $$;
            """;
        await cmd.ExecuteNonQueryAsync();

        // Add CategoryId column to NetWorthAccounts if missing (replacing old Type/IsAsset)
        cmd.CommandText = """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'NetWorthAccounts' AND column_name = 'CategoryId'
                ) THEN
                    ALTER TABLE "NetWorthAccounts" ADD COLUMN "CategoryId" integer;
                END IF;
            END $$;
            """;
        await cmd.ExecuteNonQueryAsync();

        // Seed Asset/Liability categories via SQL (needed before data migration)
        cmd.CommandText = """
            INSERT INTO "Categories" ("Name", "Icon", "Type", "Created", "CreatedBy", "LastModified", "LastModifiedBy")
            SELECT v."Name", v."Icon", v."Type", now(), NULL, now(), NULL
            FROM (VALUES
                ('Konto bankowe', 'credit-card', 2),
                ('Inwestycja', 'trending-up', 2),
                ('Kryptowaluty', 'zap', 2),
                ('Nieruchomosc', 'home', 2),
                ('Pozyczka', 'file-text', 3),
                ('Kredyt', 'alert-circle', 3)
            ) AS v("Name", "Icon", "Type")
            WHERE NOT EXISTS (
                SELECT 1 FROM "Categories" c WHERE c."Type" IN (2, 3)
            );
            """;
        await cmd.ExecuteNonQueryAsync();

        // Migrate existing NetWorthAccounts: map old Type to new CategoryId
        cmd.CommandText = """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'NetWorthAccounts' AND column_name = 'Type'
                ) THEN
                    UPDATE "NetWorthAccounts" SET "CategoryId" = (
                        SELECT "Id" FROM "Categories" WHERE "Name" = 'Konto bankowe' AND "Type" = 2 LIMIT 1
                    ) WHERE "CategoryId" IS NULL AND "Type" = 0;

                    UPDATE "NetWorthAccounts" SET "CategoryId" = (
                        SELECT "Id" FROM "Categories" WHERE "Name" = 'Inwestycja' AND "Type" = 2 LIMIT 1
                    ) WHERE "CategoryId" IS NULL AND "Type" = 1;

                    UPDATE "NetWorthAccounts" SET "CategoryId" = (
                        SELECT "Id" FROM "Categories" WHERE "Name" = 'Pozyczka' AND "Type" = 3 LIMIT 1
                    ) WHERE "CategoryId" IS NULL AND "Type" = 2;

                    UPDATE "NetWorthAccounts" SET "CategoryId" = (
                        SELECT "Id" FROM "Categories" WHERE "Name" = 'Kryptowaluty' AND "Type" = 2 LIMIT 1
                    ) WHERE "CategoryId" IS NULL AND "Type" = 3;
                END IF;

                UPDATE "NetWorthAccounts" SET "CategoryId" = (
                    SELECT "Id" FROM "Categories" WHERE "Type" = 2 LIMIT 1
                ) WHERE "CategoryId" IS NULL;
            END $$;
            """;
        await cmd.ExecuteNonQueryAsync();

        // Drop old Type column from NetWorthAccounts if exists
        cmd.CommandText = """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'NetWorthAccounts' AND column_name = 'Type'
                ) THEN
                    ALTER TABLE "NetWorthAccounts" DROP COLUMN "Type";
                END IF;
            END $$;
            """;
        await cmd.ExecuteNonQueryAsync();

        // Drop old IsAsset column from NetWorthAccounts if exists
        cmd.CommandText = """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'NetWorthAccounts' AND column_name = 'IsAsset'
                ) THEN
                    ALTER TABLE "NetWorthAccounts" DROP COLUMN "IsAsset";
                END IF;
            END $$;
            """;
        await cmd.ExecuteNonQueryAsync();

        await conn.CloseAsync();
    }

    public async Task SeedAsync()
    {
        try
        {
            await TrySeedAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "An error occurred while seeding the database.");
            throw;
        }
    }

    public async Task TrySeedAsync()
    {
        var administratorRole = new IdentityRole(Roles.Administrator);

        if (_roleManager.Roles.All(r => r.Name != administratorRole.Name))
        {
            await _roleManager.CreateAsync(administratorRole);
        }

        var administrator = new ApplicationUser
        {
            UserName = "administrator@localhost",
            Email = "administrator@localhost",
        };

        if (_userManager.Users.All(u => u.UserName != administrator.UserName))
        {
            var seedPassword = _configuration["Seed:AdminPassword"];
            if (string.IsNullOrWhiteSpace(seedPassword))
            {
                _logger.LogWarning(
                    "Seed:AdminPassword not configured — skipping admin account creation."
                );
                return;
            }
            await _userManager.CreateAsync(administrator, seedPassword);
            if (!string.IsNullOrWhiteSpace(administratorRole.Name))
            {
                await _userManager.AddToRolesAsync(administrator, new[] { administratorRole.Name });
            }
        }

        if (!_context.Categories.Any())
        {
            _context.Categories.AddRange(
                new Category
                {
                    Name = "Wynagrodzenie",
                    Icon = "briefcase",
                    Type = TransactionType.Income,
                },
                new Category
                {
                    Name = "Freelance",
                    Icon = "laptop",
                    Type = TransactionType.Income,
                },
                new Category
                {
                    Name = "Inwestycje",
                    Icon = "trending-up",
                    Type = TransactionType.Income,
                },
                new Category
                {
                    Name = "Inne przychody",
                    Icon = "plus-circle",
                    Type = TransactionType.Income,
                },
                new Category
                {
                    Name = "Jedzenie",
                    Icon = "shopping-cart",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Transport",
                    Icon = "truck",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Mieszkanie",
                    Icon = "home",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Rozrywka",
                    Icon = "film",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Zdrowie",
                    Icon = "heart",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Edukacja",
                    Icon = "book",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Ubrania",
                    Icon = "shopping-bag",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Rachunki",
                    Icon = "file-text",
                    Type = TransactionType.Expense,
                },
                new Category
                {
                    Name = "Inne wydatki",
                    Icon = "minus-circle",
                    Type = TransactionType.Expense,
                }
            );

            await _context.SaveChangesAsync(CancellationToken.None);
        }

        // Seed default Asset/Liability categories if missing
        if (
            !_context.Categories.Any(c =>
                c.Type == TransactionType.Asset || c.Type == TransactionType.Liability
            )
        )
        {
            _context.Categories.AddRange(
                new Category
                {
                    Name = "Konto bankowe",
                    Icon = "credit-card",
                    Type = TransactionType.Asset,
                },
                new Category
                {
                    Name = "Inwestycja",
                    Icon = "trending-up",
                    Type = TransactionType.Asset,
                },
                new Category
                {
                    Name = "Kryptowaluty",
                    Icon = "zap",
                    Type = TransactionType.Asset,
                },
                new Category
                {
                    Name = "Nieruchomosc",
                    Icon = "home",
                    Type = TransactionType.Asset,
                },
                new Category
                {
                    Name = "Pozyczka",
                    Icon = "file-text",
                    Type = TransactionType.Liability,
                },
                new Category
                {
                    Name = "Kredyt",
                    Icon = "alert-circle",
                    Type = TransactionType.Liability,
                }
            );

            await _context.SaveChangesAsync(CancellationToken.None);
        }
    }
}
